### ISSUE TITLE
Video Sampling needs Error Handling

### ISSUE THREAD

**Issue by txoof** [txoof/crowd_pong#3]
Currently there is absolutely no error handling. We need to add some. If the websocket server crashes, it takes down the video_capture interface as well. I think some trapping around the ws.send() call is all thiat is needed.  

`received: -0.264933046936
connection closed...
connection closed...
connection closed...
^CTraceback (most recent call last):
  File "./tornado-websocket-server.py", line 53, in <module>
    tornado.ioloop.IOLoop.instance().start()
  File "/usr/local/lib/python2.7/site-packages/tornado/ioloop.py", line 841, in start
    event_pairs = self._impl.poll(poll_timeout)
  File "/usr/local/lib/python2.7/site-packages/tornado/platform/kqueue.py", line 66, in poll
    kevents = self._kqueue.control(None, 1000, timeout)
KeyboardInterrupt`

**Comment by txoof** [comment]
The websocket server no longer takes down the video capture interface. The video capture interface outputs relevant information about the websocket status.

We may want to make the video_capture interface try to spawn the websocket server on it's own.
